services:
  api:
    environment:
      MAX_UPLOAD_BYTES: "3000000000"
  transcriber:
    gpus: !reset []
    environment:
      DEVICE: cpu
      MAX_UPLOAD_BYTES: "3000000000"
  transcriber2:
    gpus: !reset []
    environment:
      DEVICE: cpu
      MAX_UPLOAD_BYTES: "3000000000"
